### ISSUE TITLE
Braces on a new line, really?

### ISSUE THREAD

**Issue by domenic** [jsdom/js-symbol-tree#3]
I can understand strange preferences for 8-space indents. Even tabs. But newlines before braces? That is just crazy-sauce. (In part due to the `return` hazard, but also just because absolutely nobody does it.)

Feel free to close if you really want to keep this :P

**Comment by Joris-van-der-Wel** [comment]
haha. I use 8 spaces because it grants an automatic punishment if stuff gets too complex.

In javascript I use newlines before braces to differentiate between blocks and object literals:

``` javascript
let foo = {
        a: 5,
        b: 10
};

if (x > 5)
{
        doStuff(foo);
}
```

Also fun for debugging is:

``` javascript
// if (x > 5)
{
        doStuff();
}
```

Anyway, on the same line is fine with me too

**Comment by domenic** [comment]
It's your project, so if that's what you'd like, all the more power :). I just thought I'd complain to see what you thought.
