### ISSUE TITLE
Add a method to tell if a node is part of the symbol tree

### ISSUE THREAD

**Issue by domenic** [jsdom/js-symbol-tree#4]
I am running into some tricky initialization time issues in jsdom and need something like `domSymbolTree.isInitialized(node)`, so I can bail out early if we're still in the pre-symbol-tree phase.

**Comment by Joris-van-der-Wel** [comment]
Are you sure that is needed? `domSymbolTree.initialize()` is optional, any method will implicitly initialize your node as needed ([example](https://github.com/jsdom/js-symbol-tree/blob/master/test/SymbolTree.js#L84)).

This initialize function is intended to help the javascript engine optimize. v8 likes it if you always assign new properties in the same order.

**Comment by Joris-van-der-Wel** [comment]
`initialize()` is also needed for compatibility with `Object.freeze()`

**Comment by domenic** [comment]
Yeah, you're right; the problem was actually that I was passing `undefined` to `domSymbolTree.hasChildren`.
